<%@ page language="java" contentType="text/html; charset=GB18030"
    pageEncoding="GB18030"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=GB18030">
</head>

<!-- 
 This default page is designed to support several defaults:
 1. Error pages generated by Spring Boot's error configuration receive
      $timestamp, $status, $error, $message as variables - see
      org.springframework.boot.actuate.web.BasicErrorController
 2. By default, error pages setup by SimpleMappingExceptionResolver receive
      $exception
 3. We have configured our SimpleMappingExceptionResolver to setup $ex
      instead, just to show it can be done.
 -->
<body>
    <h1>Default Error Page</h1>


    <b>Page URL:</b>
    <span>${url}</span>




</body>
</html>
